version: '3.8'

services:
  face_recognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face_recognition
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    restart: always
